### ISSUE TITLE
XPrivacyLua doesn't work.

### ISSUE THREAD

**Issue by Vortelf** [android-hacker/VirtualXposed#7]
Found this on XDA. Decided to try it.
Moto G5s MM 6.0.1
Installed XPrivacyLua via apk, since the XposedInstaller provided stuck on "Waiting for Download".
Enabled and reboot, both virtualapp and phone.
When you start XPrivacyLua, it says it's needs to be fixed and redirects to XposedInstaller. List of apps is empty.

**Comment by tiann** [comment]
I have read the source code of XPrivacyLua, it hook the Settings Application(a system app) to store the module available information. But VirtualXpsoed **can not** modify system, so the implementation of XPrivacyLua can not make any sense.

**Comment by Flyhhhhhhfei** [comment]
The application is unable to run, and click anywhere after the entry is prompted to stop running

**Comment by tiann** [comment]
Built-in privacy control is working in process, #33

**Comment by M66B** [comment]
XPrivacyLua on VirtualXposed will not be supported, see [here](https://forum.xda-developers.com/showpost.php?p=76677101&postcount=2777) for more details.

**Comment by tiann** [comment]
fixed : https://github.com/M66B/XPrivacyLua/pull/3

**Comment by M66B** [comment]
Not fixed because I won't accept the pull request. See the comments of the pull request about why not.
